name: Docker Build and Push

on:
  push:
    branches:
      - main  # Main branch par push hone par chalega

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Login first
        uses: aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 034362042597.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: Build image
        run: docker build -t raja-dev .

      - name: Create tag
        run: docker tag raja-dev:latest 034362042597.dkr.ecr.ap-northeast-2.amazonaws.com/raja-dev:latest

      - name: Push Docker Image
        run: docker push 034362042597.dkr.ecr.ap-northeast-2.amazonaws.com/raja-dev:latest
# commit